# docker-compose.yml
version: '3.11-slim' 

services:
  backend:
    build:
      context: ./backend 
      dockerfile: Dockerfile
    container_name: my-web-backend 
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all 
              capabilities: [gpu]
    ports:
      - "8000:8000" 
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      STATIC_ROOT_DIR: /app/static 
    volumes:
      - ./backend:/app
      - generated_images_data:/app/static/generated_images
      - temp_session_images_data:/app/static/temp_session_images
      - model_cache:/root/.cache
      - downloaded_fonts:/app/services/image_modules/TI_modules/downloaded_fonts
    command: uvicorn app.main:app --host 0.0.0.0 --reload 

  frontend:
    build:
      context: ./frontend 
      dockerfile: Dockerfile
    container_name: my-web-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    environment:
      REACT_APP_API_BASE_URL: http://${GCP_EXTERNAL_IP}:8000
    depends_on:
      - backend 
    command: npm start

volumes:
  generated_images_data:
  temp_session_images_data:
  model_cache:
  downloaded_fonts: