openai:
  api_key_env: 여기다 OpenAI API 키를 입력하세요
  gpt_model: gpt-4.1-mini

sd_pipeline:
  text2img:
    model_id: runwayml/stable-diffusion-v1-5
  inpaint:
    model_id: runwayml/stable-diffusion-inpainting
  controlnet:
    model_id: runwayml/stable-diffusion-v1-5
  controlnet_inpaint:
    model_id: runwayml/stable-diffusion-inpainting
  torch_dtype: float16
  use_safety_checker: false
  device: cuda

lora:
  category_map:
    food:
      - name: foodphoto
        scale: 1.0
      - name: FoodPorn_v2
        scale: 0.6
    cosmetics:
      - name: e-commerce_photography02
        scale: 0.8
      - name: product_design_v3
        scale: 0.5
      - name: showcase
        scale: 0.4
    furniture:
      - name: artek_5400_lora
        scale: 1.0
      - name: showcase
        scale: 0.5

ip_adapter:
  image_encoder: "laion/CLIP-ViT-H-14-laion2B-s32B-b79K"
  checkpoint: "ip-adapter_sd15.bin"

generation:
  inference_steps: 35
  guidance_scale: 7
  negative_prompt: logo, text, watermark, blurry, extra fingers, human
  num_image: 4

paths:
  product_image: images/perfume.jfif
  reference_image: images/ref_image.png
  lora_dir: lora
  output_dir: output